name: Build App

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [26.x]
        elixir: [1.14.x]

    steps:
      - name: ☁️ Checkout repository
        uses: actions/checkout@v3

      - name: 💧 Setup Elixir ${{ matrix.elixir }} (OTP ${{matrix.otp}})
        uses: ./.github/actions
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
          build-flags: --all-warnings --warnings-as-errors

